// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQrHDmcRNpUD9oM1vbWcJOhe3UpnDobAw',
    appId: '1:136243913230:web:d4455cb417ee63d82d125f',
    messagingSenderId: '136243913230',
    projectId: 'workapp-d4e73',
    authDomain: 'workapp-d4e73.firebaseapp.com',
    storageBucket: 'workapp-d4e73.appspot.com',
    measurementId: 'G-XY1WXQKYCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_wIt_LiuoG3bvXrBTkDy2q8GjIkYe4Qg',
    appId: '1:136243913230:android:a4868b0d14f37b052d125f',
    messagingSenderId: '136243913230',
    projectId: 'workapp-d4e73',
    storageBucket: 'workapp-d4e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjC9JJzxzbNGR5vyvLMO-wNXXuo5WWS7k',
    appId: '1:136243913230:ios:f5e1dff239e89d002d125f',
    messagingSenderId: '136243913230',
    projectId: 'workapp-d4e73',
    storageBucket: 'workapp-d4e73.appspot.com',
    iosClientId: '136243913230-ejk1c191rqno18m4ceh1uk2kfh5ner35.apps.googleusercontent.com',
    iosBundleId: 'com.maanapp.maanaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjC9JJzxzbNGR5vyvLMO-wNXXuo5WWS7k',
    appId: '1:136243913230:ios:f5e1dff239e89d002d125f',
    messagingSenderId: '136243913230',
    projectId: 'workapp-d4e73',
    storageBucket: 'workapp-d4e73.appspot.com',
    iosClientId: '136243913230-ejk1c191rqno18m4ceh1uk2kfh5ner35.apps.googleusercontent.com',
    iosBundleId: 'com.maanapp.maanaap',
  );
}
